### ISSUE TITLE
Add new wireframe dataset about 100+ images

### ISSUE THREAD

**Issue by VinayChaudhari1996** [ashnkumar/sketch-code#12]
Hi guys , 

I found 100+ hand-drawn wireframe dataset and some wireframes are drawn by myself 

How I train model for new wireframe dataset and used them in this project from scratch ? 

From beginning of installion of packages to generate HTML code 

Thank you :)

**Comment by Sibylzx0** [comment]
Can I ask you that how to get hand-drawn wireframe dataset?Transfer from a html ?
Just go to README.md to know how to start your new training

**Comment by VinayChaudhari1996** [comment]
I drawn some wire-frames my own and some are collected from my friends.

**Comment by Sibylzx0** [comment]
so you make the <.gui> flie to describe the image by yourself too?

**Comment by VinayChaudhari1996** [comment]
Please send your email

**Comment by BuseYarenTekin** [comment]
Hello, how can I access the hand drawn data set?

Mail address: tekinbuseyaren@gmail.com

**Comment by abhishekbhoir81** [comment]
> I drawn some wire-frames my own and some are collected from my friends.

hey buddy can you send me dataset plz if possible email id is       
abhishekbhoir81@gmail.com

**Comment by BuseYarenTekin** [comment]
Actually, I would ask for wireframe images.
________________________________
Gönderen: abhishekbhoir81 <notifications@github.com>
Gönderildi: 4 Mart 2020 Çarşamba 23:27
Kime: ashnkumar/sketch-code <sketch-code@noreply.github.com>
Bilgi: ;BUSEYARENTEK�N <2015010205023@ogrenci.karabuk.edu.tr>; Comment <comment@noreply.github.com>
Konu: Re: [ashnkumar/sketch-code] Add new wireframe dataset about 100+ images (#12)


I drawn some wire-frames my own and some are collected from my friends.

hey buddy can you send me dataset plz if possible email id is
abhishekbhoir81@gmail.com<mailto:abhishekbhoir81@gmail.com>

**Comment by Asaddragon** [comment]
id like to request the dataset aswell
Mail address; fypgroup69@gmail.com

**Comment by BuseYarenTekin** [comment]
Excuse me, is it possible for you to share your data set with me? tekinbuseyaren@gmail.com

**Comment by VinayChaudhari1996** [comment]
Hello Guys,

Here is a datset link,

Dataset Link : https://github.com/microsoft/ailab/tree/master/Sketch2Code/model/images
Json link : https://github.com/microsoft/ailab/blob/master/Sketch2Code/model/dataset.json


Thanks

**Comment by BuseYarenTekin** [comment]
Thank you so much!
